on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          release-type: go
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          pull-request-header: ":robot: *beep* *boop* I have created a release"